# Global parameters

# absolute or relative path from the root of the repository
# tmp_directory: "tmp"

# Endpoint serving the KG to be queried 
# kg_sparql_endpoint_url: "" 

# embedding_generation:
  # Utilitary endpoint to store the ontologies (if not present in the endpoint to be queried) 
  # work_sparql_endpoint_url: ""

  # text_embedding_llm:
    # type: ollama-embeddings
    # id: mxbai-embed-large
    # vector_db: faiss
  
    # output_directory: "data/"

# Scenarios

scenario_1:
  endpoint_url: https://idsm.elixir-czech.cz/sparql/endpoint/idsm
  seq2seq_llm:
    type: ollama
    id: llama3.2:1b

    # type: ovh
    # id: Meta-Llama-3_1-70B-Instruct
    # base_url: https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/api/openai_compat/v1

    temperature: 0
    max_retries: 3 
    model_kwargs: {"top_p": 0.95 }

    
scenario_2:
  endpoint_url: https://idsm.elixir-czech.cz/sparql/endpoint/idsm
  seq2seq_llm: 
    type: ollama
    id: deepseek-r1:1.5b

    # type: ovh
    # id: Meta-Llama-3_1-70B-Instruct
    # base_url: https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/api/openai_compat/v1

    temperature: 0
    max_retries: 3 
    model_kwargs: {"top_p": 0.95 }

scenario_3:
  endpoint_url: https://idsm.elixir-czech.cz/sparql/endpoint/idsm
  seq2seq_llm:
    type: ollama
    id: deepseek-r1:1.5b

    # type: ovh
    # id: Meta-Llama-3_1-70B-Instruct
    # base_url: https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/api/openai_compat/v1
    temperature: 0
    max_retries: 3 
    model_kwargs: {"top_p": 0.95 }
  text_embedding_llm:
    type: ollama-embeddings
    # type: openai-embeddings
    id: nomic-embed-text
    vector_db: faiss
    # vector_db: chroma

scenario_4:
  endpoint_url: https://idsm.elixir-czech.cz/sparql/endpoint/idsm
  seq2seq_llm: 
    type: ollama
    id: deepseek-r1:1.5b

    # type: ovh
    # id: Meta-Llama-3_1-70B-Instruct
    # base_url: https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/api/openai_compat/v1

    temperature: 0
    max_retries: 3 
    model_kwargs: {"top_p": 0.95 }
  text_embedding_llm:
    type: ollama-embeddings
    # type: openai-embeddings
    id: nomic-embed-text
    vector_db: faiss
    # vector_db: chroma

scenario_5:
  endpoint_url: https://idsm.elixir-czech.cz/sparql/endpoint/idsm
  seq2seq_llm:
    type: ollama
    id: deepseek-r1:1.5b

    # type: ovh
    # id: Meta-Llama-3_1-70B-Instruct
    # base_url: https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/api/openai_compat/v1

    temperature: 0
    max_retries: 3 
    model_kwargs: {"top_p": 0.95 }
  text_embedding_llm:
    type: ollama-embeddings
    # type: openai-embeddings
    id: nomic-embed-text
    vector_db: faiss
    # vector_db: chroma

scenario_6:
  endpoint_url: https://idsm.elixir-czech.cz/sparql/endpoint/idsm
  seq2seq_llm:
    # type: ovh
    # id: Meta-Llama-3_1-70B-Instruct
    # base_url: https://llama-3-1-70b-instruct.endpoints.kepler.ai.cloud.ovh.net/api/openai_compat/v1
    
    # type: deepseek
    # base_url: https://api.deepseek.com
    # id: deepseek-chat
    # id: deepseek-reasoner

    type: ollama
    id: deepseek-r1:1.5b

    type: hugface
    # id: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
    
    temperature: 0
    max_retries: 3 
    model_kwargs: {"top_p": 0.95 }
  text_embedding_llm:
    type: ollama-embeddings
    # type: openai-embeddings
    id: nomic-embed-text
    vector_db: faiss
    # vector_db: chroma

