version: 1
formatters:
  simple:
    format: '%(name)s %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s %(name)s %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: './logs/kgbot_app.log'
    maxBytes: 1000000
    backupCount: 5

loggers:
  app:
      level: DEBUG
      handlers: [console,file_handler]
      propagate: no
  langgraph_api:
      level: WARN
      handlers: [console]
  langgraph_storage:
      level: WARN
      handlers: [console]

root:
  level: INFO
  handlers: [console,file_handler]
